name: ASMP Backend

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_DB: asmp_db
          POSTGRES_USER: asmp_user
          POSTGRES_PASSWORD: arush
        ports:
          - 5432:5432
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Migrations
        env:
          DATABASE_URL: postgresql://asmp_user:arush@localhost/asmp_db
        run: |
          cd backend
          source venv/bin/activate
          python manage.py migrate

      - name: Run Tests
        run: |
          cd backend
          source venv/bin/activate
          python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Deploy Backend
        run: echo "Deploying Django Backend..."