# Generated by Django 5.1.6 on 2025-03-05 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsmpUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('preference1', models.CharField(blank=True, max_length=255, null=True)),
                ('preference2', models.CharField(blank=True, max_length=255, null=True)),
                ('preference3', models.CharField(blank=True, max_length=255, null=True)),
                ('preference4', models.CharField(blank=True, max_length=255, null=True)),
                ('preference5', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
